### PR TITLE
Add vertical splitting

### PR DESCRIPTION
**Pull request by RodMontgomery**
I finally figured out that the appearance of Vertical Example 2 is actually correct, given the CSS.

Some Day I may know enough CSS to make another Vertical Example, in which there are no margins around the inner, vertically-split panes of the left horizontally-split pane.

### CODE REVIEW

**Comment by nathancahill** [comment]
So, I'm thinking about this approach, and not sure it's the best to have two functions (Split and SplitV) with lots of overlap. Instead, the better way would be to have an option called `direction`:

```
Split(['one', 'two'], {
    direction: 'vertical'
}
```
Then in the code, use `options.direction` to choose behavior between the two. What do you think

**Comment by RodMontgomery** [comment]
I don't understand "with lots of overlap".

Certainly the structures of the two functions are parallel -- indeed, at one point I thought about writing a function that converts the source program for one into the source program for the other -- but I don't see how to write a single function that handles both directions, without making it either a nasty mess of evals or an even more nasty mess of if(direction == 'vertical') { ... } else { ... }

I also noticed that the vertical splitting has a bottom-edge-creeping-upward problem that is the exact counterpart of the right-edge-creeping-left problem you fixed. This, despite that I copied the pattern of your properly-working horizontal-splitting code exactly! Hmmm... I wonder whether the margins around the inner panes are causing the creeping? The purely-vertically-split Vertical Example 1 does not creep.

**Comment by RodMontgomery** [comment]
Figured out what's going on with Vertical Example 2. The reason for the strangeness is that the CSS sets padding for .split and .vsplit, to move the text in from the edge. Works fine as long as the only thing inside is text, but when there's another split inside, the padding messes up the size calculations -- see http://www.w3schools.com/css/css_boxmodel.asp and http://www.w3schools.com/css/css_dimension.asp for details.

The fix is to remove the padding from .split and .vsplit and put padding on p elements instead.

**Comment by nathancahill** [comment]
This looks great.

**Comment by nathancahill** [comment]
Still thinking that since the functions are almost identical, except for the direction the operate on, something like a `direction` option should be used instead.

**Comment by RodMontgomery** [comment]
Still not seeing how to do that in readable code. :frowning:

**Comment by nathancahill** [comment]
Ok, just merged your changes in. Only needed 5 more `if` statements (8f9deb6) once I generalized the variable names (035f0ea). Going to close this since I couldn't merge directly, but adding you as a contributor for your work on this. Thanks!

**Pull request closed without merging**
