### PR TITLE
:memo: :lipstick: cursors look better if they indicate the direction of movement

### PR DESCRIPTION
**Pull request by basarat**
Visual : 

image

Great project :rose: :+1:

### CODE REVIEW

**Comment by nathancahill** [comment]
Thanks! This is why the CSS is completely customizable, there is no project default. I'm going to close this, but I appreciate the pull request!

**Comment by adamjimenez** [comment]
Surely these are more sensible defaults, though.

**Comment by nathancahill** [comment]
You're absolutely right.

**Comment by basarat** [comment]
> You're absolutely right.

Cheers :rose:

**Comment by nathancahill** [comment]
Released in 1.0.6. Thanks!

**Pull request merged**
