### PR TITLE
Making `adjust` function configurable

### PR DESCRIPTION
**Pull request by ambischof**
I really like the interface for this tool but I don't want to use percentages to specify my layout. There are several different ways of applying the width split and I acknowledge that this plugin can't adapt to all of them, so it would be great to be able to customize the adjust function. 

Goal is to optionally be able to specify adjust function as

```
var adjustFn = function(offset){
    //custom adjust logic
}
Split([el1, el2], {adjust: adjustFn})
```

Please respond with any feedback. Thank you!

### CODE REVIEW

**Comment by nathancahill** [comment]
Split.js uses percentages so that the parent can be resized without breaking the layout. Fixed pixel sizes (that's what your custom adjust logic would be right?) breaks pretty quickly.

**Comment by ambischof** [comment]
What about flexbox, though?

**Comment by nathancahill** [comment]
Ah, very good point. I'll look at adding flexbox support.

**Comment by ambischof** [comment]
Flexbox was my intention, of another way would work, that would be fine. I felt exposing the adjust function would give the developer the most flexibility and be the least opinionated.

**Comment by nathancahill** [comment]
Implemented in 1.1.3 with some changes (you can see the commit here: [b229e41](https://github.com/nathancahill/Split.js/commit/b229e4106b743b393a6ffbfbded746af1d3227cc#diff-1a170fe88c675dcb5554c9de478f6da2)). See the new configuration options `elementStyle` and `gutterStyle` (https://github.com/nathancahill/Split.js#elementstyle) and an example with how to use them with flexbox: https://github.com/nathancahill/Split.js#flexbox.

Thanks!

**Pull request closed without merging**
