### PR TITLE
Added possibility to expand/collapse

### PR DESCRIPTION
**Pull request by tlozynskyy**

### CODE REVIEW

**Comment by amnevins** [comment]
Hey awesome, thanks for adding this functionality!  Can you provide some examples on how to use these new methods please?

**Comment by sitalakshmi-narayanan** [comment]
Hi
Great that you have this functionality merged on to this!
It would be awesome if you can help us with some examples. Please!!!

**Comment by tlozynskyy** [comment]
Split(["#first", "#second"], {
                sizes: [17, 83],
                minSize: [230, 1000],
                gutterSize: 5,
                collapsedSize: 20
            });
There are two main functions (collapse/expand)  for this functionality, which  are toggling the class of the element to  .collapsed/.expanded

Some styling:
.gutter .collapsed {
        background-color: red;
    }
.gutter .expanded{
  background-color: green;
}

**Comment by nathancahill** [comment]
Thanks for the PR @tlozynskyy! I went ahead an implemented something similar, with a few more features in this release. The API now works like this:

```js
var instance = Split([], ...)
instance.collapse(0)
instance.collapse(1)
```
where `0` and `1` are the indexes for the elements in the split.

Additionally, it's possible to update the sizes now:
```js
instance.setSizes([10, 40, 50])
```
Closing this since I believe this addresses your needs.

**Pull request closed without merging**
